# all optional, the values given here are the defaults
meta_property_name: tags
tag_overview_path: ''
tag_separator: ','
tag_overview_layout: pages/default.pug

# examples
tag_overview_default_image: /img/banner/banner.jpg
tag_overview_website_image: /img/banner/website-banner.jpg
