# all optional, the values given here are the defaults
meta_property_name: tags
tag_overview_path: '/tags'
tag_separator: ','
tag_overview_layout: pages/default.pug
tag_overview_meta:
  keywords: some, tag, related, keys
  description: This is an overview page

# examples
tag_overview_default_image: /img/banner/banner.jpg
tag_overview_website_image: /img/banner/website-banner.jpg
